/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hausaufgabe_1;

public class App {
    public String getGreeting() {
        return null;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
